vaadin/vaadin-notification-flow

- pom.xml
- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationIT.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTest.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
add needed dependency to pom;
add IT tests;
add unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/6)
> Add Notification component support

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/7)
> remove flow-HTML-components dependency

- pom.xml
- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationIT.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTest.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/8)
> Improve Javadoc on component support

- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationIT.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTest.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
This feature *cannot* be released with flow `1.0.0.alpha15`, as the needed `webjar` is not there.
add generated Notification alpha4 and reimplement setPosition() method
the build will not pass, untill https://github.com/vaadin/flow/pull/3226 got merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/9)
> reimplement setPosition

- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationIT.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTest.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
add demo;
add unit test;
add IT test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/11)
> Add static Convenience method for notification

- src/test/java/com/vaadin/flow/component/notification/tests/NotificationIT.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/12)
> fix import in IT tests

- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/14)
> Update generated component and add lumo style to demos

- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/16)
> Attach the notification to the dom automatically

- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationIT.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTest.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/22)
> Revise Notification api.

- pom.xml
- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
enable logging;
remove HtmlImport from component demo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/23)
> Using new webjars

- pom.xml
- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationWithTemplateIT.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationWithTemplatePage.java
- src/test/java/com/vaadin/flow/component/notification/tests/TestTemplate.java
- src/test/webapp/frontend/src/test-template.html
Related to vaadin/flow#3513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/26)
> Fix for Notifications with a PolymerTemplate inside. Added tests.

- pom.xml
- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
update new generated code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/35)
> Update vaadin-notification webjars to use 1.0.0-beta2

- pom.xml
- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/36)
> Update webjars to 1.0.0-beta3

- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
fix after vaadin/flow#3678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/37)
> Update generated code

- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTest.java
Fixes #17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/38)
> Add check against null for UI instance

- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
Fixes #25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/40)
> Add show() method overload

- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
Update demo for #25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/41)
> Update demo for the static convenience method

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/42)
> Update vaadin-notification to 1.0.0-beta4

- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/45)
> Remove hasStyle from the generated notification

- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationIT.java
Fixes #44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/46)
> Add demo for styling content of a Notification

- pom.xml
- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/47)
> Update webjars and generated code

- src/main/java/com/vaadin/flow/component/notification/Notification.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/52)
> Use content container as a virtualChild.

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/56)
> Fix flow dependency type

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/58)
> Update README about branching scheme

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/60)
> Update to webjars with material theme

- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
Add tests;
part of vaadin/flow#4437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/63)
> Correct the APIs for adding Component at index

- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
Fixes #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/64)
> Replace setText related deferred job logic

- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
Fixes #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/68)
> Add an explicit duration for every notification in demo

- src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java
Fixes #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/69)
> Add an explicit duration for every notification in demo (#68)

- src/main/java/com/vaadin/flow/component/notification/Notification.java
- src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java
- src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
Part of the fix for #4600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/70)
> Make addComponentAtIndex logic FW8 compatible

- src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/73)
> Update java wrapper to stable version

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/77)
> flow.version = 1.3-SNAPSHOT

- pom.xml
- vaadin-notification-flow-demo/pom.xml
- vaadin-notification-flow-integration-tests/pom.xml
- vaadin-notification-flow-testbench/pom.xml
- vaadin-notification-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/80)
> Update to next minor and Use flow 1.5-SNAPSHOT

- vaadin-notification-flow-integration-tests/pom.xml
- vaadin-notification-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/86)
> Make TB artifactId consistent with other components

- vaadin-notification-flow-integration-tests/pom-bower-mode.xml
- vaadin-notification-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/89)
> Clean up integration tests deps and correct bower mode deps

- vaadin-notification-flow/pom.xml
- vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
update lumo webjar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/90)
> Update npm component version

- pom.xml
- vaadin-notification-flow-integration-tests/pom-bower-mode.xml
- vaadin-notification-flow-testbench/pom.xml
- vaadin-notification-flow/pom.xml
- vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
- vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/92)
> Remove vaadin-components-testbench

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/93)
> Use testbench from flow-component-base

- vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/94)
> fix a typo

- vaadin-notification-flow-demo/src/main/java/com/vaadin/flow/component/notification/demo/NotificationView.java
This issue is for users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files
> Adding missing method to Vaadin Notification demos

- pom.xml
- vaadin-notification-flow-demo/pom.xml
- vaadin-notification-flow-integration-tests/pom-bower-mode.xml
- vaadin-notification-flow-integration-tests/pom.xml
- vaadin-notification-flow-testbench/pom.xml
- vaadin-notification-flow/pom.xml
- vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
> Bump versions for V14.3
